### PR TITLE
add esx_joblogs compatibility

### PR DESCRIPTION
**Pull request by RedAlex**
add esx_joblogs compatibility
https://github.com/ESX-PUBLIC/esx_joblogs

### CODE REVIEW

**Comment by LuaDeldu** [comment]
esx_joblogs is not an official esx resource. I don't think they will let you merge the compatibility changes.

**Comment by RedAlex** [comment]
I know, however, that I have coded the simplest possible compatibility to increase the chances of it being accepted.

**Comment by ddh3** [comment]
I’ll leace this for Hawaii to review, but I 100% percent support this logging idea due to the fact we are having issues on our server with people steeling.

**Comment by majormarcin** [comment]
@ElPumpo  in my opinion a good place to add the esx_joblogs function is esx_service because it will probably be used in other works, especially police and ambulance (in the second one not yet from what I know) but esx_service would have an additional function

**Comment by RedAlex** [comment]
If you want to use my work/idea to create an official version i have no problem with this, i have create this to help people,

**Pull request closed without merging**
