### PR TITLE
fix search and id not working/opening

### PR DESCRIPTION
**Pull request by polarim**
notify still doesn't activate, but who cares, just add notify = true to top of function if you really want that

### CODE REVIEW

**Comment by Tiimon** [comment]
Wasn't able to get these changes to work on my end, did you only change the code in server.lua?

**Comment by polarim** [comment]
I will double check, but it was the only change I remember making to make it work, give me a little bit to go through it again.

**Comment by polarim** [comment]
Just checked, doesn't seem to be any other changes relevant to this section.  Do you have any errors, missing commas, etc?  

If this fix doesn't work for everyone, then I'll close it until I can try and solve the phantom issue some people seem to have.

**Comment by Tiimon** [comment]
Are you running the most recent policejob using the download button on GitHub or are you using the most recent release which is from 2018

**Comment by polarim** [comment]
why would I download this any other way than the clone/download button on github

**Pull request closed without merging**
