### PR TITLE
Easy commits: czech language & improvement of requirements

### LINKED ISSUE #201: Support for Czech language
I would like to add support for Czech language.

### PR DESCRIPTION
**Pull request by celestian**
Resolves #201

### CODE REVIEW

**Comment by redoper1** [comment]
You have translated job name from 'police' to 'policie' and job grade names too in the DB, that will result in that this script will not work without further edits to the script on the Czech translation users side. It needs that values in original form.

**Comment by celestian** [comment]
@redoper1 Thanks, addressed. (New patch provided.)
I will test it later today.

**Comment by celestian** [comment]
It works now, but Czech special characters are not displayed well. It could be fixed by DB character set. I will look at it later.

**Comment by celestian** [comment]
I see, that i created this PR from master. I will open it again, separately for both issues.

**Pull request closed without merging**
