### PR TITLE
Fixed Vehicle Plate info not showing.

### PR DESCRIPTION
**Pull request by mortdudley**
Was receiving error in console when players were checking vehicle information in the job menu:

>SCRIPT ERROR: @esx_policejob/server/main.lua:214: attempt to index a nil value (local 'result2')
> ref (@esx_policejob/server/main.lua:214)
>  (@mysql-async/mysql-async.js:14959)

Removed "name" from lines 211 and 238. Tested and working ok.

### CODE REVIEW

**Comment by ElPumpo** [comment]
Well that wont work

**Comment by mortdudley** [comment]
Worked fine for me. Maybe there's more to it that I have missed? Essentially it seems that it wasn't working because it was trying to pull the Steam name of the owner from the name column that you removed from the user table. Once I removed name, it started working fine.

**Comment by ElPumpo** [comment]
Do you think its selected for no reason from database??

**Comment by mortdudley** [comment]
Have you even tested it? Why would it be selecting name from the user table if the name column no longer exists?

**Comment by ElPumpo** [comment]
You realize that its still used in this script?! If you read one line below the one you change you can obviously see that it is in use, no? I cant teach you how to read code

**Comment by mortdudley** [comment]
It doesn't change the fact that it's calling for info from a column that doesn't exist. All it means is that lines 218 and 245 need to be altered to match.

The reason I didn't pick it up initially is because you cannot create a character on our server without a firstname and lastname, so it tested fine. That was my mistake.

**Comment by ElPumpo** [comment]
It does still not change the fact that your "fix" will work with esx identity disabled

**Comment by mortdudley** [comment]
So do you have any suggestions at all? I'm not professing to be an expert here, just trying to help where I can.

**Comment by ElPumpo** [comment]
And if it is using a old column why would you ever expect just not selecting it would ever fix anything?

**Comment by mortdudley** [comment]
My understanding when looking at it was that it was asking for the character's name in firstname and lastname and the steam name in name. As ESX no longer keeps steam names in the name column, I figured it was what was causing this issue as the script was calling for information that doesn't exist.

Like I said, I'm not coming at this from the point of view of an expert, just as someone who has had a relatively successful time reverse engineering things when needed. I'm also not trying to be combative, just trying to be helpful. 

Would you be able to assist me with understanding why it is asking for the name column if the name column doesn't exist any more?

**Comment by ElPumpo** [comment]
There we go, co authored you with a working fix. Also I noticed that one of the callbacks were essentially the same so I merged them.

**Pull request closed without merging**
